name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML file syntax
        run: |
          echo "Checking index.html syntax..."
          if grep -q "<html" index.html; then
            echo "HTML file looks fine!"
          else
            echo "HTML file does not contain <html> tag!"
            exit 1
          fi

      - name: Upload index.html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html-file
          path: index.html
